version: "2"
run:
  concurrency: 4
  build-tags:
    - e2e
  modules-download-mode: vendor
linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: sync/atomic
              desc: use type-safe atomics from go.uber.org/atomic
    funlen:
      lines: 80
      statements: 40
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - mnd
          - revive
        path: _test\.go
      - linters:
          - gocyclo
        path: scalers_builder.go
      - linters:
          - gocyclo
        path: scale_scaledobjects.go
      - linters:
          - dupl
        path: triggerauthentication_controller.go
      - linters:
          - gocritic
        text: 'unnecessaryDefer:'
      - linters:
          - staticcheck
        text: 'ST1000:'
      - linters:
          - bodyclose
        path: azure/azure_app_insights.go
      - linters:
          - dupl
        path: nats_jetstream_scaler.go
      - linters:
          - dupl
        path: stan_scaler.go
      - linters:
          - gocyclo
        path: datadog_scaler.go
      - linters:
          - gocyclo
        path: kafka_scaler.go
      - linters:
          - gocyclo
        path: apache_kafka_scaler.go
      - linters:
          - dupl
        path: couchdb_scaler.go
      - linters:
          - dupl
        path: mongo_scaler.go
      - linters:
          - gocritic
        path: azure_pipelines_scaler.go
      - linters:
          - depguard
        path: pkg/scalers/external_mock_scaler.go
      - linters:
          - depguard
          - goconst
        path: controllers/keda/scaledobject_controller_test.go
      - linters:
          - depguard
        path: pkg/scalers/external_scaler_test.go
      - linters:
          - gocyclo
        path: pkg/scaling/resolver/scale_resolvers.go
      - linters:
          - dupl
        path: pkg/scalers/azure/azure_storage.go
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/kedacore/keda)
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
      - cmd/operator/main.go
      - cmd/webhooks/main.go
      - controllers/keda/suite_test.go
      - apis/keda/v1alpha1/scaledobject_webhook_test.go
